alter table Student drop constraint FKf12myy73nsf6soln9xli8th80
drop table if exists Address cascade
drop table if exists Student cascade
alter table Student drop constraint FKf12myy73nsf6soln9xli8th80
drop table if exists Address cascade
drop table if exists Student cascade
alter table Student drop constraint FKf12myy73nsf6soln9xli8th80
drop table if exists Address cascade
drop table if exists Student cascade
alter table Student drop constraint FKf12myy73nsf6soln9xli8th80
drop table if exists Address cascade
drop table if exists Student cascade
alter table Phone drop constraint FK8p74wyfckl9p9p9d7h5y0a9ea
alter table Student drop constraint FKf12myy73nsf6soln9xli8th80
drop table if exists Address cascade
drop table if exists Phone cascade
drop table if exists Student cascade
alter table phone drop constraint FKlxixtpg4l6cepxnm9yifgr09d
alter table Student drop constraint FKf12myy73nsf6soln9xli8th80
drop table if exists Address cascade
drop table if exists phone cascade
drop table if exists Student cascade
alter table Address drop constraint FK4q6j38bhikrv1pjbmde52gg7
alter table phone drop constraint FKlxixtpg4l6cepxnm9yifgr09d
alter table Student drop constraint FKf12myy73nsf6soln9xli8th80
drop table if exists Address cascade
drop table if exists phone cascade
drop table if exists Student cascade
alter table phone drop constraint FKlxixtpg4l6cepxnm9yifgr09d
alter table Student drop constraint FKf12myy73nsf6soln9xli8th80
drop table if exists Address cascade
drop table if exists phone cascade
drop table if exists Student cascade
alter table class_Student drop constraint FK7y4m2ruo06syx1a0hkcwbwpt
alter table class_Student drop constraint FKriny34u6qj3de5fj6iwjio419
alter table phone drop constraint FKlxixtpg4l6cepxnm9yifgr09d
alter table Student drop constraint FKf12myy73nsf6soln9xli8th80
drop table if exists Address cascade
drop table if exists class cascade
drop table if exists class_Student cascade
drop table if exists phone cascade
drop table if exists Student cascade
alter table class_Student drop constraint FK7y4m2ruo06syx1a0hkcwbwpt
alter table class_Student drop constraint FKriny34u6qj3de5fj6iwjio419
alter table phone drop constraint FKlxixtpg4l6cepxnm9yifgr09d
alter table Student drop constraint FKf12myy73nsf6soln9xli8th80
drop table if exists Address cascade
drop table if exists class cascade
drop table if exists class_Student cascade
drop table if exists phone cascade
drop table if exists Student cascade
alter table class_Student drop constraint FK7y4m2ruo06syx1a0hkcwbwpt
alter table class_Student drop constraint FKriny34u6qj3de5fj6iwjio419
alter table phone drop constraint FKlxixtpg4l6cepxnm9yifgr09d
alter table Student drop constraint FKf12myy73nsf6soln9xli8th80
drop table if exists Address cascade
drop table if exists class cascade
drop table if exists class_Student cascade
drop table if exists phone cascade
drop table if exists Student cascade
alter table Klass_Student drop constraint FK141vmi2elh0b4f8y38496gpx5
alter table Klass_Student drop constraint FKpgby4imfrc9p9tp2eeudvsdtf
alter table phone drop constraint FKlxixtpg4l6cepxnm9yifgr09d
alter table Student drop constraint FKf12myy73nsf6soln9xli8th80
drop table if exists Address cascade
drop table if exists Klass cascade
drop table if exists Klass_Student cascade
drop table if exists phone cascade
drop table if exists Student cascade
alter table Klass_Student drop constraint FK141vmi2elh0b4f8y38496gpx5
alter table Klass_Student drop constraint FKpgby4imfrc9p9tp2eeudvsdtf
alter table phone drop constraint FKlxixtpg4l6cepxnm9yifgr09d
alter table Student drop constraint FKf12myy73nsf6soln9xli8th80
drop table if exists Address cascade
drop table if exists Klass cascade
drop table if exists Klass_Student cascade
drop table if exists phone cascade
drop table if exists Student cascade
alter table Klass_Student drop constraint FK141vmi2elh0b4f8y38496gpx5
alter table Klass_Student drop constraint FKpgby4imfrc9p9tp2eeudvsdtf
alter table phone drop constraint FKlxixtpg4l6cepxnm9yifgr09d
alter table Student drop constraint FKf12myy73nsf6soln9xli8th80
drop table if exists Address cascade
drop table if exists Klass cascade
drop table if exists Klass_Student cascade
drop table if exists phone cascade
drop table if exists Student cascade
alter table Address drop constraint FK4q6j38bhikrv1pjbmde52gg7
alter table Klass_Student drop constraint FK141vmi2elh0b4f8y38496gpx5
alter table Klass_Student drop constraint FKpgby4imfrc9p9tp2eeudvsdtf
alter table phone drop constraint FKlxixtpg4l6cepxnm9yifgr09d
alter table Student drop constraint FKf12myy73nsf6soln9xli8th80
drop table if exists Address cascade
drop table if exists Klass cascade
drop table if exists Klass_Student cascade
drop table if exists phone cascade
drop table if exists Student cascade
alter table Klass_Student drop constraint FK141vmi2elh0b4f8y38496gpx5
alter table Klass_Student drop constraint FKpgby4imfrc9p9tp2eeudvsdtf
alter table phone drop constraint FKlxixtpg4l6cepxnm9yifgr09d
alter table Student drop constraint FKf12myy73nsf6soln9xli8th80
drop table if exists Address cascade
drop table if exists Klass cascade
drop table if exists Klass_Student cascade
drop table if exists phone cascade
drop table if exists Student cascade
alter table Klass_Student drop constraint FK141vmi2elh0b4f8y38496gpx5
alter table Klass_Student drop constraint FKpgby4imfrc9p9tp2eeudvsdtf
alter table phone drop constraint FKlxixtpg4l6cepxnm9yifgr09d
alter table Student drop constraint FKf12myy73nsf6soln9xli8th80
drop table if exists Address cascade
drop table if exists Klass cascade
drop table if exists Klass_Student cascade
drop table if exists phone cascade
drop table if exists Student cascade
alter table Address drop constraint FK4q6j38bhikrv1pjbmde52gg7
alter table Klass_Student drop constraint FK141vmi2elh0b4f8y38496gpx5
alter table Klass_Student drop constraint FKpgby4imfrc9p9tp2eeudvsdtf
alter table phone drop constraint FKlxixtpg4l6cepxnm9yifgr09d
alter table Student drop constraint FKf12myy73nsf6soln9xli8th80
drop table if exists Address cascade
drop table if exists Klass cascade
drop table if exists Klass_Student cascade
drop table if exists phone cascade
drop table if exists Student cascade
alter table Address drop constraint FK4q6j38bhikrv1pjbmde52gg7
alter table Klass_Student drop constraint FK141vmi2elh0b4f8y38496gpx5
alter table Klass_Student drop constraint FKpgby4imfrc9p9tp2eeudvsdtf
alter table phone drop constraint FKlxixtpg4l6cepxnm9yifgr09d
alter table Student drop constraint FKf12myy73nsf6soln9xli8th80
drop table if exists Address cascade
drop table if exists Klass cascade
drop table if exists Klass_Student cascade
drop table if exists phone cascade
drop table if exists Student cascade
alter table Address drop constraint FK4q6j38bhikrv1pjbmde52gg7
alter table Klass_Student drop constraint FK141vmi2elh0b4f8y38496gpx5
alter table Klass_Student drop constraint FKpgby4imfrc9p9tp2eeudvsdtf
alter table phone drop constraint FKlxixtpg4l6cepxnm9yifgr09d
alter table Student drop constraint FKf12myy73nsf6soln9xli8th80
drop table if exists Address cascade
drop table if exists Klass cascade
drop table if exists Klass_Student cascade
drop table if exists phone cascade
drop table if exists Student cascade
alter table Address drop constraint FK4q6j38bhikrv1pjbmde52gg7
alter table Klass_Student drop constraint FK141vmi2elh0b4f8y38496gpx5
alter table Klass_Student drop constraint FKpgby4imfrc9p9tp2eeudvsdtf
alter table phone drop constraint FKlxixtpg4l6cepxnm9yifgr09d
alter table Student drop constraint FKf12myy73nsf6soln9xli8th80
drop table if exists Address cascade
drop table if exists Klass cascade
drop table if exists Klass_Student cascade
drop table if exists phone cascade
drop table if exists Student cascade
alter table Address drop constraint FK4q6j38bhikrv1pjbmde52gg7
alter table Klass_Student drop constraint FK141vmi2elh0b4f8y38496gpx5
alter table Klass_Student drop constraint FKpgby4imfrc9p9tp2eeudvsdtf
alter table phone drop constraint FKlxixtpg4l6cepxnm9yifgr09d
alter table Student drop constraint FKf12myy73nsf6soln9xli8th80
drop table if exists Address cascade
drop table if exists Klass cascade
drop table if exists Klass_Student cascade
drop table if exists phone cascade
drop table if exists Student cascade
alter table Address drop constraint FK4q6j38bhikrv1pjbmde52gg7
alter table Klass_Student drop constraint FK141vmi2elh0b4f8y38496gpx5
alter table Klass_Student drop constraint FKpgby4imfrc9p9tp2eeudvsdtf
alter table phone drop constraint FKlxixtpg4l6cepxnm9yifgr09d
alter table Student drop constraint FKf12myy73nsf6soln9xli8th80
drop table if exists Address cascade
drop table if exists Klass cascade
drop table if exists Klass_Student cascade
drop table if exists phone cascade
drop table if exists Student cascade
alter table Address drop constraint FK4q6j38bhikrv1pjbmde52gg7
alter table Klass_Student drop constraint FK141vmi2elh0b4f8y38496gpx5
alter table Klass_Student drop constraint FKpgby4imfrc9p9tp2eeudvsdtf
alter table phone drop constraint FKlxixtpg4l6cepxnm9yifgr09d
alter table Student drop constraint FKf12myy73nsf6soln9xli8th80
drop table if exists Address cascade
drop table if exists Klass cascade
drop table if exists Klass_Student cascade
drop table if exists phone cascade
drop table if exists Student cascade
alter table Klass_Student drop constraint FK141vmi2elh0b4f8y38496gpx5
alter table Klass_Student drop constraint FKpgby4imfrc9p9tp2eeudvsdtf
alter table phone drop constraint FKlxixtpg4l6cepxnm9yifgr09d
alter table Student drop constraint FK7h7k8tcc911knoug1c78k6m17
drop table if exists Address cascade
drop table if exists Klass cascade
drop table if exists Klass_Student cascade
drop table if exists phone cascade
drop table if exists Student cascade
